apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: jenkins-agent-nodejs-lts
  annotations:
    description: This template deploys a Jenkins agent to build Node.js based projects with the latest Long-Term-Solution (LTS) version and latest version of npm and npx
    iconClass: icon-jenkins
    openshift.io/display-name: Jenkins Agent Node.js (LTS)
    openshift.io/documentation-url: https://github.com/simongolms/ods-jenkins-agent-nodejs
    openshift.io/provider-display-name: Simon Golms
    openshift.io/support-url: https://github.com/simongolms/ods-jenkins-agent-nodejs
    tags: "jenkins,agent,nodejs"
  labels:
    template: jenkins-agent-nodejs-lts
labels:
  app: jenkins-agent-nodejs-lts
  component: jenkins-agent
  part-of: jenkins-agent-nodejs
  template: jenkins-agent-nodejs-lts
parameters:
  - name: APP_DNS
    value: ""
  - name: AQUASEC_SCANNERCLI_URL
    value: ""
  - name: NEXUS_AUTH
    value: ""
  - name: NEXUS_URL
    value: ""
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: jenkins-agent-nodejs-lts
    spec:
      dockerImageRepository: jenkins-agent-nodejs-lts
      lookupPolicy:
        local: true
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: jenkins-agent-nodejs-lts
    spec:
      failedBuildsHistoryLimit: 5
      output:
        to:
          kind: ImageStreamTag
          name: jenkins-agent-nodejs-lts:latest
      source:
        git:
          ref: main
          uri: https://github.com/simongolms/ods-jenkins-agent-nodejs.git
        type: Git
      strategy:
        dockerStrategy:
          buildArgs:
            - name: APP_DNS
              value: ${APP_DNS}
            - name: AQUASEC_SCANNERCLI_URL
              value: ${AQUASEC_SCANNERCLI_URL}
            - name: NEXUS_AUTH
              value: ${NEXUS_AUTH}
            - name: NEXUS_URL
              value: ${NEXUS_URL}
            - name: NODEJS_VERSION
              value: lts.x
            - name: NPM_VERSION
              value:
          dockerfilePath: Dockerfile
        type: Docker
      successfulBuildsHistoryLimit: 5
      triggers:
        - type: "ConfigChange"
message: >-
  The image is built in your active namespace and is named `jenkins-agent-nodejs-lts`.

  It can be referenced in a `Jenkinsfile` with `<NAMESPACE>/jenkins-agent-nodejs-lts:latest`.
